[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/admin.html"
  [headers.values]
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer"
